In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a[0]

1

In [5]:
a.shape

(3,)

In [6]:
a[1] = 10

In [7]:
a[1]

10

In [8]:
b = np.array([[1,2,3],[4,5,6]])

In [9]:
b.shape

(2, 3)

In [10]:
b[0,2]

3

In [11]:
sefr = np.zeros((4,5))

In [12]:
sefr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
yek = np.ones((2,3))

In [14]:
yek

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ident = np.identity(9)

In [16]:
ident

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [21]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [22]:
a[2:,:]

array([[ 9, 10, 11, 12]])

In [24]:
np.sum(a[2:,:])

42

In [25]:
np.sum(a[:2], axis=1)

array([10, 26])

In [26]:
np.min(a[2])

9

In [27]:
np.mean(a)

6.5